#!/usr/bin/env node
/**
 * build-tokens.mjs — generate src/styles/tokens.css from tokens/tokens.json
 *
 * The single source of truth for the Bottke Clinical Design System (Brand Kit B).
 * Walks the DTCG token tree and emits one `:root { ... }` block. The CSS variable
 * name is the token's LEAF KEY verbatim (e.g. `ox-deep` -> `--ox-deep`), NOT the
 * dotted group path — this preserves the exact variable contract the guide's CSS
 * already depends on. Group nesting is for human organisation only.
 *
 * Guarantees:
 *   - every leaf has a `$value` (errors otherwise)
 *   - no two leaves share a name (collision guard — the whole point of unifying
 *     the previously-duplicated `.rx-root` / `.sx-root` blocks)
 *
 * Usage:  node scripts/build-tokens.mjs   (npm run tokens)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "tokens/tokens.json");
const OUT = resolve(ROOT, "src/styles/tokens.css");

const META = new Set(["$schema", "$description", "$type", "$value"]);

/** Depth-first collect every {$value} leaf as [leafKey, value, description]. */
function collect(node, key, acc) {
  if (node && typeof node === "object" && "$value" in node) {
    acc.push({ name: key, value: String(node.$value), desc: node.$description || "" });
    return acc;
  }
  if (node && typeof node === "object") {
    for (const k of Object.keys(node)) {
      if (META.has(k)) continue;
      collect(node[k], k, acc);
    }
  }
  return acc;
}

const json = JSON.parse(readFileSync(SRC, "utf8"));
const tokens = collect(json, "$root", []);

// Validate: no missing values, no duplicate variable names.
const seen = new Map();
const dupes = [];
for (const t of tokens) {
  if (!t.value) throw new Error(`token "${t.name}" has no $value`);
  if (seen.has(t.name)) dupes.push(t.name);
  seen.set(t.name, t.value);
}
if (dupes.length) throw new Error(`duplicate token name(s): ${[...new Set(dupes)].join(", ")}`);

const longest = Math.max(...tokens.map((t) => t.name.length));
const lines = tokens.map((t) => {
  const pad = " ".repeat(longest - t.name.length);
  const comment = t.desc ? `  /* ${t.desc} */` : "";
  return `  --${t.name}:${pad} ${t.value};${comment}`;
});

const css = `/* AUTOGENERATED by scripts/build-tokens.mjs — do not edit by hand.
   Source: tokens/tokens.json   ·   ${tokens.length} tokens
   Edit the JSON and run \`npm run tokens\`. */
:root {
${lines.join("\n")}
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css, "utf8");
console.log(`build-tokens: wrote ${tokens.length} tokens -> ${OUT.replace(ROOT + "/", "")}`);
